services:  
  - docker

language: python
python:
  - "2.7"

deploy:
  provider: gae
  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
  project: "YOUR PROJECT ID"

notifications:
  email:
    on_success: never
    on_failure: always
    
script:
  - ls