runtime: python37

handlers:
# index files
- url: /([^.]+?)/?$  # urls with no dot in them
  static_files: www/\1/index.html
  upload: www/(.+)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: www/index.html
  upload: www/index.html
  expiration: "15m"

# everything else
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)