runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: www/index.html
  upload: www/index.html
  secure: always
  redirect_http_response_code: 301

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: www/\1/index.html
  upload: www/.*/index.html
  secure: always
  redirect_http_response_code: 301
  
# Handle all php files
- url: /(.+.php)
  script: auto
  secure: always
  redirect_http_response_code: 301  

# HF test fun  
- url: /hf_test
  script: www/charlie/hfqdb_rss/main.app

# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  redirect_http_response_code: 301