runtime: php72

handlers:
- url: /$
  static_files: www/index.html
  upload: www/index.html
  secure: always
  redirect_http_response_code: 301

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: www/\1/index.html
  upload: www/.*/index.html
  secure: always
  redirect_http_response_code: 301
  
# Handle all php files
- url: /(.+.php)
  script: auto
  secure: always
  redirect_http_response_code: 301  
  
# Handle all py files
- url: /(.+.py)
  secure: always
  redirect_http_response_code: 301
  
# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  redirect_http_response_code: 301